name: bookstore
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  sms_autofill: ^2.4.0
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^8.2.8
  pinput: ^5.0.0
  intl: any
  share_plus: any
  expandable_text: any
  calendar_date_picker2: any
  flutter_rating_bar: any
  image_picker: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts: 
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
